export const MOCK_TASKS = [
  { id: "task-001", name: "Summarize weekly emails", description: "Fetch and summarize all unread emails from the past week", status: "completed", priority: "high", adapter: "gmail", createdAt: new Date(Date.now() - 86400000 * 3).toISOString(), updatedAt: new Date(Date.now() - 3600000).toISOString(), runCount: 12, lastRunAt: new Date(Date.now() - 3600000).toISOString(), tags: ["email", "summary", "weekly"], idempotencyKey: "weekly-email-summary-v1", writeSafe: false },
  { id: "task-002", name: "Sync calendar events to Notion", description: "Pull today's calendar events and create Notion entries", status: "running", priority: "medium", adapter: "gcal", createdAt: new Date(Date.now() - 86400000).toISOString(), updatedAt: new Date(Date.now() - 60000).toISOString(), runCount: 5, lastRunAt: new Date(Date.now() - 60000).toISOString(), tags: ["calendar", "notion", "sync"], idempotencyKey: "cal-notion-sync-daily", writeSafe: true },
  { id: "task-003", name: "Review and triage GitHub PRs", description: "Analyze open pull requests and add triage labels", status: "awaiting_approval", priority: "high", adapter: "github", createdAt: new Date(Date.now() - 86400000 * 2).toISOString(), updatedAt: new Date(Date.now() - 1800000).toISOString(), runCount: 3, lastRunAt: new Date(Date.now() - 1800000).toISOString(), tags: ["github", "pr", "review"], idempotencyKey: "gh-pr-triage-v2", writeSafe: false },
  { id: "task-004", name: "Draft Slack standup message", description: "Compose and send daily standup to #engineering channel", status: "failed", priority: "medium", adapter: "slack", createdAt: new Date(Date.now() - 86400000 * 5).toISOString(), updatedAt: new Date(Date.now() - 7200000).toISOString(), runCount: 8, lastRunAt: new Date(Date.now() - 7200000).toISOString(), tags: ["slack", "standup", "daily"], idempotencyKey: "slack-standup-daily", writeSafe: false },
  { id: "task-005", name: "Archive old Notion pages", description: "Find Notion pages older than 90 days and archive them", status: "pending", priority: "low", adapter: "notion", createdAt: new Date(Date.now() - 86400000 * 7).toISOString(), updatedAt: new Date(Date.now() - 86400000).toISOString(), runCount: 0, lastRunAt: undefined, tags: ["notion", "archive"], idempotencyKey: "notion-archive-90d", writeSafe: true },
  { id: "task-006", name: "Crawl documentation sites", description: "Crawl and index updated documentation for knowledge base", status: "paused", priority: "low", adapter: "web", createdAt: new Date(Date.now() - 86400000 * 10).toISOString(), updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(), runCount: 2, lastRunAt: new Date(Date.now() - 86400000 * 2).toISOString(), tags: ["web", "crawl", "docs"], idempotencyKey: "docs-crawl-weekly", writeSafe: false },
];

export const MOCK_RUNS = [
  { id: "run-001", taskId: "task-001", taskName: "Summarize weekly emails", status: "completed", startedAt: new Date(Date.now() - 3600000 * 2).toISOString(), completedAt: new Date(Date.now() - 3600000).toISOString(), durationMs: 3600000, retryCount: 0, maxRetries: 3, output: "Summarized 47 emails across 8 threads. Key items: 3 action items, 2 meeting requests.", adapter: "gmail", llmModel: "gpt-4o", tokenCount: 12400, idempotencyKey: "weekly-email-summary-v1", isStale: false },
  { id: "run-002", taskId: "task-002", taskName: "Sync calendar events to Notion", status: "running", startedAt: new Date(Date.now() - 60000).toISOString(), completedAt: undefined, durationMs: undefined, retryCount: 0, maxRetries: 3, output: undefined, adapter: "gcal", llmModel: "claude-3-5-haiku", tokenCount: 0, idempotencyKey: "cal-notion-sync-daily", isStale: false },
  { id: "run-003", taskId: "task-004", taskName: "Draft Slack standup message", status: "failed", startedAt: new Date(Date.now() - 7200000).toISOString(), completedAt: new Date(Date.now() - 7100000).toISOString(), durationMs: 100000, retryCount: 3, maxRetries: 3, error: "Slack API rate limit exceeded: 429 Too Many Requests", adapter: "slack", llmModel: "gpt-4o-mini", tokenCount: 842, idempotencyKey: "slack-standup-daily", isStale: false },
  { id: "run-004", taskId: "task-001", taskName: "Summarize weekly emails", status: "completed", startedAt: new Date(Date.now() - 86400000).toISOString(), completedAt: new Date(Date.now() - 86400000 + 1800000).toISOString(), durationMs: 1800000, retryCount: 0, maxRetries: 3, output: "Summarized 31 emails. 1 urgent action item flagged.", adapter: "gmail", llmModel: "gpt-4o", tokenCount: 9100, idempotencyKey: "weekly-email-summary-v1-prev", isStale: true },
  { id: "run-005", taskId: "task-003", taskName: "Review and triage GitHub PRs", status: "retrying", startedAt: new Date(Date.now() - 1800000).toISOString(), completedAt: undefined, durationMs: undefined, retryCount: 1, maxRetries: 3, error: "GitHub token expired", adapter: "github", llmModel: "claude-3-5-sonnet", tokenCount: 2800, idempotencyKey: "gh-pr-triage-v2", isStale: false },
  { id: "run-006", taskId: "task-006", taskName: "Crawl documentation sites", status: "stale", startedAt: new Date(Date.now() - 86400000 * 2).toISOString(), completedAt: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(), durationMs: 3600000, retryCount: 0, maxRetries: 3, output: "Indexed 142 pages across 3 documentation sites.", adapter: "web", llmModel: "gpt-4o-mini", tokenCount: 18200, idempotencyKey: "docs-crawl-weekly", isStale: true },
];

export const MOCK_COMMANDS = [
  { id: "cmd-001", name: "Send email reply", description: "Reply to John's email about the Q4 roadmap meeting", type: "external_call", status: "awaiting_approval", isHighRisk: false, requiresApproval: true, idempotencyKey: "email-reply-john-q4-001", writeSafe: false, groupId: "grp-001", adapter: "gmail", createdAt: new Date(Date.now() - 1800000).toISOString(), executedAt: undefined, payload: { to: "john@example.com", subject: "Re: Q4 roadmap" } },
  { id: "cmd-002", name: "Create GitHub issue", description: "File bug report for authentication timeout regression", type: "write", status: "completed", isHighRisk: false, requiresApproval: false, idempotencyKey: "gh-issue-auth-timeout-v1", writeSafe: true, groupId: "grp-001", adapter: "github", createdAt: new Date(Date.now() - 3600000).toISOString(), executedAt: new Date(Date.now() - 3500000).toISOString(), payload: { title: "Auth timeout regression in v2.4.1" }, result: { issueNumber: 1247, url: "https://github.com/org/repo/issues/1247" } },
  { id: "cmd-003", name: "Delete Slack message", description: "Remove accidentally posted draft message from #general", type: "delete", status: "awaiting_approval", isHighRisk: true, requiresApproval: true, idempotencyKey: "slack-delete-msg-abc123", writeSafe: false, groupId: undefined, adapter: "slack", createdAt: new Date(Date.now() - 600000).toISOString(), executedAt: undefined, payload: { channel: "#general", messageTs: "1714500000.123456" } },
  { id: "cmd-004", name: "Archive Notion database rows", description: "Archive 23 stale project entries from the Projects database", type: "write", status: "completed", isHighRisk: false, requiresApproval: false, idempotencyKey: "notion-archive-projects-batch-04", writeSafe: true, groupId: "grp-002", adapter: "notion", createdAt: new Date(Date.now() - 86400000).toISOString(), executedAt: new Date(Date.now() - 86000000).toISOString(), payload: { databaseId: "db-xyz", rowCount: 23 }, result: { archived: 23, skipped: 0 } },
  { id: "cmd-005", name: "Merge pull request", description: "Merge feature/auth-refactor into main after CI passes", type: "external_call", status: "pending", isHighRisk: true, requiresApproval: true, idempotencyKey: "gh-merge-pr-842", writeSafe: false, groupId: undefined, adapter: "github", createdAt: new Date(Date.now() - 300000).toISOString(), executedAt: undefined, payload: { repo: "org/repo", prNumber: 842 } },
  { id: "cmd-006", name: "Fetch calendar events", description: "Read calendar events for next 7 days", type: "read", status: "completed", isHighRisk: false, requiresApproval: false, idempotencyKey: "gcal-read-7d-001", writeSafe: true, groupId: "grp-002", adapter: "gcal", createdAt: new Date(Date.now() - 7200000).toISOString(), executedAt: new Date(Date.now() - 7100000).toISOString(), payload: { calendarId: "primary", days: 7 }, result: { eventCount: 14 } },
];

export const MOCK_GROUPS = [
  { id: "grp-001", name: "Email + GitHub triage batch", description: "Reply to pending emails and file GitHub issues from weekly review", status: "partial", commandCount: 2, completedCount: 1, failedCount: 0, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: "grp-002", name: "Notion + Calendar cleanup", description: "Archive old Notion entries and sync calendar for the week", status: "completed", commandCount: 2, completedCount: 2, failedCount: 0, createdAt: new Date(Date.now() - 86400000).toISOString() },
];

export const MOCK_APPROVALS = [
  { id: "appr-001", title: "Delete Slack message from #general", description: "OmegaBot wants to delete a draft message accidentally posted to #general channel.", status: "pending", riskLevel: "high", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 600000).toISOString(), expiresAt: new Date(Date.now() + 3000000).toISOString(), commandId: "cmd-003", taskId: "task-004", adapter: "slack", payload: { channel: "#general", preview: "Draft: Hey team, don't forget..." } },
  { id: "appr-002", title: "Send email reply to john@example.com", description: "Reply to John's email thread about Q4 roadmap planning session.", status: "pending", riskLevel: "medium", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 1800000).toISOString(), expiresAt: new Date(Date.now() + 7200000).toISOString(), commandId: "cmd-001", taskId: "task-001", adapter: "gmail", payload: { to: "john@example.com", subject: "Re: Q4 roadmap" } },
  { id: "appr-003", title: "Merge PR #842: feature/auth-refactor", description: "Merge the auth refactor branch into main using squash merge. CI is passing.", status: "pending", riskLevel: "critical", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 300000).toISOString(), expiresAt: new Date(Date.now() + 14400000).toISOString(), commandId: "cmd-005", taskId: "task-003", adapter: "github", payload: { repo: "org/repo", prNumber: 842, branch: "feature/auth-refactor" } },
  { id: "appr-004", title: "Post standup to #engineering", description: "Send daily standup summary to the #engineering Slack channel.", status: "approved", riskLevel: "low", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 86400000).toISOString(), expiresAt: new Date(Date.now() - 79200000).toISOString(), decidedAt: new Date(Date.now() - 85000000).toISOString(), decidedBy: "operator", reason: "Approved for daily routine", commandId: "cmd-prev-001", taskId: "task-004", adapter: "slack" },
  { id: "appr-005", title: "Archive 156 Notion pages", description: "Archive all Notion pages older than 90 days with no recent edits.", status: "rejected", riskLevel: "high", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 172800000).toISOString(), expiresAt: new Date(Date.now() - 100800000).toISOString(), decidedAt: new Date(Date.now() - 169000000).toISOString(), decidedBy: "operator", reason: "Too broad — please scope to Projects database only", commandId: "cmd-prev-002", taskId: "task-005", adapter: "notion" },
  { id: "appr-006", title: "Create 12 calendar events from emails", description: "Parse meeting requests from email and create calendar events for next week.", status: "expired", riskLevel: "medium", requestedBy: "omegabot-runtime", requestedAt: new Date(Date.now() - 259200000).toISOString(), expiresAt: new Date(Date.now() - 172800000).toISOString(), commandId: "cmd-prev-003", taskId: "task-002", adapter: "gcal" },
];

export const MOCK_EVENTS = [
  { id: "evt-001", type: "task.started", level: "info", message: "Task 'Sync calendar events to Notion' started", taskId: "task-002", taskName: "Sync calendar events to Notion", runId: "run-002", adapter: "gcal", timestamp: new Date(Date.now() - 60000).toISOString(), metadata: { adapter: "gcal", llmModel: "claude-3-5-haiku" } },
  { id: "evt-002", type: "approval.requested", level: "warning", message: "High-risk approval requested: Delete Slack message from #general", taskId: "task-004", taskName: "Draft Slack standup message", commandId: "cmd-003", adapter: "slack", timestamp: new Date(Date.now() - 600000).toISOString(), metadata: { riskLevel: "high", expiresIn: "50m" } },
  { id: "evt-003", type: "command.completed", level: "success", message: "Command 'Create GitHub issue' completed — issue #1247 created", taskId: "task-003", taskName: "Review and triage GitHub PRs", runId: "run-005", commandId: "cmd-002", adapter: "github", timestamp: new Date(Date.now() - 3500000).toISOString(), metadata: { issueNumber: 1247, writeSafe: true } },
  { id: "evt-004", type: "run.failed", level: "error", message: "Run failed: Slack API rate limit exceeded (429) after 3 retries", taskId: "task-004", taskName: "Draft Slack standup message", runId: "run-003", adapter: "slack", timestamp: new Date(Date.now() - 7100000).toISOString(), metadata: { retryCount: 3, maxRetries: 3, error: "429 Too Many Requests" } },
  { id: "evt-005", type: "task.completed", level: "success", message: "Task 'Summarize weekly emails' completed — 47 emails processed", taskId: "task-001", taskName: "Summarize weekly emails", runId: "run-001", adapter: "gmail", timestamp: new Date(Date.now() - 3600000).toISOString(), metadata: { emailCount: 47, actionItems: 3, tokenCount: 12400 } },
  { id: "evt-006", type: "adapter.health_check", level: "warning", message: "Adapter 'slack' health degraded: latency spike detected (2400ms)", adapter: "slack", timestamp: new Date(Date.now() - 300000).toISOString(), metadata: { latencyMs: 2400, threshold: 1000 } },
  { id: "evt-007", type: "llm.call", level: "info", message: "LLM call via openai/gpt-4o: 2400 tokens in 1.2s", taskId: "task-001", taskName: "Summarize weekly emails", runId: "run-001", adapter: "gmail", timestamp: new Date(Date.now() - 3650000).toISOString(), metadata: { model: "gpt-4o", tokens: 2400, latencyMs: 1200, cost: 0.024 } },
  { id: "evt-008", type: "run.retry", level: "warning", message: "Run retrying (attempt 1/3): GitHub token expired", taskId: "task-003", taskName: "Review and triage GitHub PRs", runId: "run-005", adapter: "github", timestamp: new Date(Date.now() - 1700000).toISOString(), metadata: { retryCount: 1, maxRetries: 3, error: "GitHub token expired" } },
  { id: "evt-009", type: "adapter.connected", level: "success", message: "Adapter 'github' reconnected after token refresh", adapter: "github", timestamp: new Date(Date.now() - 1600000).toISOString(), metadata: { previousStatus: "error", newStatus: "connected" } },
  { id: "evt-010", type: "approval.rejected", level: "warning", message: "Approval rejected: Archive 156 Notion pages — scope too broad", taskId: "task-005", adapter: "notion", timestamp: new Date(Date.now() - 169000000).toISOString(), metadata: { reason: "Too broad" } },
];

export const MOCK_ADAPTERS = [
  { id: "adapter-gmail", name: "Gmail", type: "email", status: "connected", health: { status: "healthy", latencyMs: 145, lastChecked: new Date(Date.now() - 60000).toISOString(), message: "All systems operational" }, permissions: ["read:email", "send:email", "manage:labels"], version: "2.1.0", lastActivity: new Date(Date.now() - 3600000).toISOString(), commandCount: 47, errorRate: 0.02, description: "Google Gmail adapter for reading, sending, and managing emails", requiresCredentials: true, credentialsConfigured: true },
  { id: "adapter-gcal", name: "Google Calendar", type: "calendar", status: "connected", health: { status: "healthy", latencyMs: 112, lastChecked: new Date(Date.now() - 60000).toISOString(), message: "All systems operational" }, permissions: ["read:events", "write:events"], version: "1.4.2", lastActivity: new Date(Date.now() - 60000).toISOString(), commandCount: 23, errorRate: 0.01, description: "Google Calendar adapter", requiresCredentials: true, credentialsConfigured: true },
  { id: "adapter-github", name: "GitHub", type: "github", status: "connected", health: { status: "degraded", latencyMs: 890, lastChecked: new Date(Date.now() - 120000).toISOString(), message: "Token recently refreshed; monitoring latency" }, permissions: ["read:repos", "write:issues", "write:prs"], version: "3.0.1", lastActivity: new Date(Date.now() - 1600000).toISOString(), commandCount: 34, errorRate: 0.08, description: "GitHub adapter for repos, issues, PRs", requiresCredentials: true, credentialsConfigured: true },
  { id: "adapter-slack", name: "Slack", type: "custom", status: "degraded", health: { status: "degraded", latencyMs: 2400, lastChecked: new Date(Date.now() - 300000).toISOString(), message: "Elevated latency — possible rate limiting" }, permissions: ["read:messages", "write:messages"], version: "2.2.0", lastActivity: new Date(Date.now() - 600000).toISOString(), commandCount: 62, errorRate: 0.15, description: "Slack adapter for channels and messages", requiresCredentials: true, credentialsConfigured: true },
  { id: "adapter-notion", name: "Notion", type: "files", status: "connected", health: { status: "healthy", latencyMs: 230, lastChecked: new Date(Date.now() - 60000).toISOString(), message: "All systems operational" }, permissions: ["read:pages", "write:pages"], version: "1.2.0", lastActivity: new Date(Date.now() - 86400000).toISOString(), commandCount: 18, errorRate: 0.03, description: "Notion adapter for pages and databases", requiresCredentials: true, credentialsConfigured: true },
  { id: "adapter-web", name: "Web Crawler", type: "web", status: "disconnected", health: { status: "unknown", latencyMs: undefined, lastChecked: new Date(Date.now() - 86400000 * 2).toISOString(), message: "Adapter paused" }, permissions: ["read:web"], version: "1.0.4", lastActivity: new Date(Date.now() - 86400000 * 2).toISOString(), commandCount: 5, errorRate: 0.0, description: "Web crawling adapter", requiresCredentials: false, credentialsConfigured: true },
  { id: "adapter-custom-01", name: "Internal API", type: "custom", status: "error", health: { status: "unhealthy", latencyMs: undefined, lastChecked: new Date(Date.now() - 600000).toISOString(), message: "Connection refused: internal API unreachable" }, permissions: ["read:data", "write:data"], version: "0.9.1", lastActivity: new Date(Date.now() - 3600000 * 4).toISOString(), commandCount: 3, errorRate: 0.67, description: "Custom adapter for internal company API", requiresCredentials: true, credentialsConfigured: false },
];

export const MOCK_LLM_MODELS = [
  { id: "gpt-4o", name: "GPT-4o", provider: "openai", contextWindow: 128000, isDefault: true, status: "available", costPer1kTokens: 0.005, avgLatencyMs: 1200, capabilities: ["text", "vision", "function-calling", "json-mode"] },
  { id: "gpt-4o-mini", name: "GPT-4o Mini", provider: "openai", contextWindow: 128000, isDefault: false, status: "available", costPer1kTokens: 0.00015, avgLatencyMs: 450, capabilities: ["text", "vision", "function-calling"] },
  { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet", provider: "anthropic", contextWindow: 200000, isDefault: false, status: "available", costPer1kTokens: 0.003, avgLatencyMs: 980, capabilities: ["text", "vision", "function-calling", "extended-thinking"] },
  { id: "claude-3-5-haiku", name: "Claude 3.5 Haiku", provider: "anthropic", contextWindow: 200000, isDefault: false, status: "available", costPer1kTokens: 0.0008, avgLatencyMs: 380, capabilities: ["text", "vision", "function-calling"] },
  { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", provider: "google", contextWindow: 1000000, isDefault: false, status: "available", costPer1kTokens: 0.0001, avgLatencyMs: 320, capabilities: ["text", "vision", "long-context"] },
  { id: "llama-3.3-70b", name: "Llama 3.3 70B", provider: "local", contextWindow: 131072, isDefault: false, status: "rate_limited", costPer1kTokens: 0.0, avgLatencyMs: 2100, capabilities: ["text", "function-calling"] },
];

export const MOCK_LLM_ROUTES = [
  { id: "route-001", name: "High-risk actions → GPT-4o", condition: "task.isHighRisk == true", targetModelId: "gpt-4o", targetModelName: "GPT-4o", priority: 1, enabled: true, matchCount: 23, createdAt: new Date(Date.now() - 86400000 * 30).toISOString() },
  { id: "route-002", name: "Simple reads → GPT-4o Mini", condition: "command.type == 'read' AND task.priority != 'critical'", targetModelId: "gpt-4o-mini", targetModelName: "GPT-4o Mini", priority: 2, enabled: true, matchCount: 189, createdAt: new Date(Date.now() - 86400000 * 25).toISOString() },
  { id: "route-003", name: "Long-context tasks → Gemini Flash", condition: "task.tags includes 'long-context'", targetModelId: "gemini-2.0-flash", targetModelName: "Gemini 2.0 Flash", priority: 3, enabled: true, matchCount: 7, createdAt: new Date(Date.now() - 86400000 * 14).toISOString() },
  { id: "route-004", name: "Calendar tasks → Claude Haiku", condition: "task.adapter == 'gcal'", targetModelId: "claude-3-5-haiku", targetModelName: "Claude 3.5 Haiku", priority: 4, enabled: true, matchCount: 41, createdAt: new Date(Date.now() - 86400000 * 20).toISOString() },
  { id: "route-005", name: "Code review tasks → Claude Sonnet", condition: "task.tags includes 'code-review'", targetModelId: "claude-3-5-sonnet", targetModelName: "Claude 3.5 Sonnet", priority: 5, enabled: false, matchCount: 0, createdAt: new Date(Date.now() - 86400000 * 7).toISOString() },
];

export const MOCK_LLM_USAGE = {
  totalTokens: 1284200, promptTokens: 892400, completionTokens: 391800, totalRequests: 847, avgLatencyMs: 1140, last24hTokens: 48300, last7dTokens: 312400,
  byModel: [
    { modelId: "gpt-4o", modelName: "GPT-4o", tokens: 612000, requests: 312, cost: 3.06 },
    { modelId: "gpt-4o-mini", modelName: "GPT-4o Mini", tokens: 384200, requests: 421, cost: 0.058 },
    { modelId: "claude-3-5-haiku", modelName: "Claude 3.5 Haiku", tokens: 142800, requests: 89, cost: 0.114 },
    { modelId: "claude-3-5-sonnet", modelName: "Claude 3.5 Sonnet", tokens: 98400, requests: 18, cost: 0.295 },
    { modelId: "gemini-2.0-flash", modelName: "Gemini 2.0 Flash", tokens: 46800, requests: 7, cost: 0.005 },
  ],
};

export const MOCK_INTEGRATIONS = [
  { id: "int-gmail", name: "Gmail", category: "communication", status: "connected", description: "Read, send, and manage emails.", permissions: ["Read emails", "Send emails", "Manage labels"], lastSync: new Date(Date.now() - 3600000).toISOString(), isBuiltin: true },
  { id: "int-gcal", name: "Google Calendar", category: "calendar", status: "connected", description: "Create and manage calendar events.", permissions: ["Read events", "Create events", "Manage calendars"], lastSync: new Date(Date.now() - 60000).toISOString(), isBuiltin: true },
  { id: "int-github", name: "GitHub", category: "developer", status: "connected", description: "Interact with GitHub repos, issues, PRs.", permissions: ["Read repos", "Create issues", "Manage PRs"], lastSync: new Date(Date.now() - 1600000).toISOString(), webhookUrl: "https://omegabot.app/hooks/github", isBuiltin: true },
  { id: "int-slack", name: "Slack", category: "communication", status: "connected", description: "Read and post messages across channels.", permissions: ["Read messages", "Post messages", "Manage channels"], lastSync: new Date(Date.now() - 600000).toISOString(), webhookUrl: "https://omegabot.app/hooks/slack", isBuiltin: true },
  { id: "int-notion", name: "Notion", category: "productivity", status: "connected", description: "Read and write Notion pages and databases.", permissions: ["Read pages", "Write pages", "Read databases"], lastSync: new Date(Date.now() - 86400000).toISOString(), isBuiltin: true },
  { id: "int-openai", name: "OpenAI", category: "ai", status: "connected", description: "Access GPT models for text and tool use.", permissions: ["Chat completions", "Embeddings", "Function calling"], lastSync: new Date(Date.now() - 120000).toISOString(), isBuiltin: true },
  { id: "int-anthropic", name: "Anthropic", category: "ai", status: "connected", description: "Access Claude models for complex reasoning.", permissions: ["Messages API", "Tool use", "Vision"], lastSync: new Date(Date.now() - 120000).toISOString(), isBuiltin: true },
  { id: "int-google-ai", name: "Google AI", category: "ai", status: "connected", description: "Access Gemini models for long-context tasks.", permissions: ["Generate content", "Vision"], lastSync: new Date(Date.now() - 120000).toISOString(), isBuiltin: true },
  { id: "int-linear", name: "Linear", category: "developer", status: "disconnected", description: "Manage Linear issues, cycles, and projects.", permissions: ["Read issues", "Create issues", "Manage projects"], isBuiltin: false },
  { id: "int-jira", name: "Jira", category: "developer", status: "disconnected", description: "Create and manage Jira tickets and sprints.", permissions: ["Read issues", "Create issues"], isBuiltin: false },
  { id: "int-gdrive", name: "Google Drive", category: "storage", status: "disconnected", description: "Read and create Drive files and folders.", permissions: ["Read files", "Create files", "Manage folders"], isBuiltin: false },
  { id: "int-hubspot", name: "HubSpot", category: "productivity", status: "pending", description: "Manage CRM contacts, deals, and campaigns.", permissions: ["Read contacts", "Update contacts", "Read deals"], isBuiltin: false },
];

export const MOCK_CHANGE_PLANS = [
  { id: "cp-001", title: "Refactor authentication middleware", description: "Extract auth logic into a dedicated auth service with token rotation support.", status: "pending_review", repository: "org/backend-api", branch: "feature/auth-refactor", prUrl: "https://github.com/org/backend-api/pull/842", prNumber: 842, riskLevel: "high", filesChanged: 14, additions: 342, deletions: 187, createdAt: new Date(Date.now() - 86400000).toISOString(), updatedAt: new Date(Date.now() - 3600000).toISOString(), reviewers: ["alice", "bob"], taskId: "task-003" },
  { id: "cp-002", title: "Add rate limiting to API endpoints", description: "Implement sliding window rate limiting using Redis.", status: "approved", repository: "org/backend-api", branch: "feature/rate-limiting", prUrl: "https://github.com/org/backend-api/pull/831", prNumber: 831, riskLevel: "medium", filesChanged: 6, additions: 128, deletions: 14, createdAt: new Date(Date.now() - 86400000 * 3).toISOString(), updatedAt: new Date(Date.now() - 86400000).toISOString(), reviewers: ["carol"], taskId: "task-003" },
  { id: "cp-003", title: "Fix database connection pool exhaustion", description: "Increase pool size and add connection timeout handling.", status: "applied", repository: "org/backend-api", branch: "fix/db-pool-exhaustion", prUrl: "https://github.com/org/backend-api/pull/819", prNumber: 819, riskLevel: "critical", filesChanged: 3, additions: 45, deletions: 12, createdAt: new Date(Date.now() - 86400000 * 7).toISOString(), updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(), reviewers: ["alice", "dave"], taskId: "task-001" },
  { id: "cp-004", title: "Add OpenTelemetry tracing", description: "Instrument key code paths with OpenTelemetry spans.", status: "draft", repository: "org/backend-api", branch: "feature/otel-tracing", riskLevel: "low", filesChanged: 0, additions: 0, deletions: 0, createdAt: new Date(Date.now() - 3600000).toISOString(), updatedAt: new Date(Date.now() - 3600000).toISOString(), reviewers: [], taskId: "task-002" },
  { id: "cp-005", title: "Update dependencies to latest versions", description: "Automated dependency update: express, zod, drizzle-orm, pino, and 8 others.", status: "rejected", repository: "org/backend-api", branch: "deps/automated-update-may-2025", prUrl: "https://github.com/org/backend-api/pull/838", prNumber: 838, riskLevel: "medium", filesChanged: 2, additions: 47, deletions: 47, createdAt: new Date(Date.now() - 86400000 * 2).toISOString(), updatedAt: new Date(Date.now() - 86400000).toISOString(), reviewers: ["bob"], taskId: "task-001" },
];

export const MOCK_ARTIFACTS = [
  { id: "art-001", name: "weekly-email-summary.md", type: "markdown", size: 4823, taskId: "task-001", taskName: "Summarize weekly emails", runId: "run-001", createdAt: new Date(Date.now() - 3600000).toISOString(), mimeType: "text/markdown", tags: ["email", "summary", "weekly"] },
  { id: "art-002", name: "calendar-events-export.json", type: "json", size: 8241, taskId: "task-002", taskName: "Sync calendar events to Notion", runId: "run-002", createdAt: new Date(Date.now() - 60000).toISOString(), mimeType: "application/json", tags: ["calendar", "export"] },
  { id: "art-003", name: "pr-triage-report.md", type: "markdown", size: 12800, taskId: "task-003", taskName: "Review and triage GitHub PRs", runId: "run-005", createdAt: new Date(Date.now() - 1800000).toISOString(), mimeType: "text/markdown", tags: ["github", "pr", "triage"] },
  { id: "art-004", name: "crawl-index-results.csv", type: "csv", size: 31400, taskId: "task-006", taskName: "Crawl documentation sites", runId: "run-006", createdAt: new Date(Date.now() - 86400000 * 2).toISOString(), mimeType: "text/csv", tags: ["web", "crawl"] },
  { id: "art-005", name: "auth-refactor-analysis.md", type: "markdown", size: 7200, taskId: "task-003", taskName: "Review and triage GitHub PRs", runId: "run-005", createdAt: new Date(Date.now() - 1600000).toISOString(), mimeType: "text/markdown", tags: ["github", "code-review"] },
  { id: "art-006", name: "standup-draft.txt", type: "text", size: 892, taskId: "task-004", taskName: "Draft Slack standup message", runId: "run-003", createdAt: new Date(Date.now() - 7100000).toISOString(), mimeType: "text/plain", tags: ["slack", "standup"] },
  { id: "art-007", name: "notion-archive-plan.json", type: "json", size: 3120, taskId: "task-005", taskName: "Archive old Notion pages", createdAt: new Date(Date.now() - 86400000).toISOString(), mimeType: "application/json", tags: ["notion", "archive"] },
];

export const MOCK_SETTINGS = {
  systemName: "OmegaBot", defaultLlmModelId: "gpt-4o", requireApprovalForHighRisk: true, approvalTimeoutMinutes: 60, maxConcurrentTasks: 5, maxRetries: 3, retryDelayMs: 5000, stalenessThresholdMs: 3600000, logLevel: "info", enableEventStreaming: true, webhookUrl: "", enableIdempotency: true, version: "0.23.0",
};

export const MOCK_OVERVIEW = {
  activeTasks: 2, completedToday: 8, failedToday: 1, pendingApprovals: 3, adaptersHealthy: 4, adaptersDegraded: 2, adaptersTotal: 7, totalRunsToday: 12, avgRunDurationMs: 1840000, tokensUsedToday: 48300,
  recentActivity: MOCK_EVENTS.slice(0, 5),
  tasksByStatus: [
    { status: "running", count: 1 }, { status: "completed", count: 3 }, { status: "failed", count: 1 },
    { status: "awaiting_approval", count: 1 }, { status: "pending", count: 1 }, { status: "paused", count: 1 },
  ],
  runTrend: Array.from({ length: 12 }, (_, i) => ({
    hour: new Date(Date.now() - 3600000 * (11 - i)).toISOString(),
    count: [3, 5, 2, 4, 7, 6, 8, 4, 9, 11, 7, 2][i],
    failed: [0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0][i],
  })),
};
