import { Router } from "express";

const router = Router();

const INTEGRATIONS: Record<string, unknown>[] = [
  {
    id: "int-gmail",
    name: "Gmail",
    category: "communication",
    status: "connected",
    description: "Read, send, and manage emails through your Gmail account.",
    permissions: ["Read emails", "Send emails", "Manage labels", "Access attachments"],
    lastSync: new Date(Date.now() - 3600000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-gcal",
    name: "Google Calendar",
    category: "calendar",
    status: "connected",
    description: "Create, read, and manage calendar events and reminders.",
    permissions: ["Read events", "Create events", "Update events", "Manage calendars"],
    lastSync: new Date(Date.now() - 60000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-github",
    name: "GitHub",
    category: "developer",
    status: "connected",
    description: "Interact with GitHub repos, issues, PRs, Actions, and more.",
    permissions: ["Read repos", "Create issues", "Manage pull requests", "Read Actions"],
    lastSync: new Date(Date.now() - 1600000).toISOString(),
    webhookUrl: "https://omegabot.app/hooks/github",
    isBuiltin: true,
  },
  {
    id: "int-slack",
    name: "Slack",
    category: "communication",
    status: "connected",
    description: "Read and post messages across Slack workspaces and channels.",
    permissions: ["Read messages", "Post messages", "Manage channels", "Manage files"],
    lastSync: new Date(Date.now() - 600000).toISOString(),
    webhookUrl: "https://omegabot.app/hooks/slack",
    isBuiltin: true,
  },
  {
    id: "int-notion",
    name: "Notion",
    category: "productivity",
    status: "connected",
    description: "Read and write Notion pages, databases, and blocks.",
    permissions: ["Read pages", "Write pages", "Read databases", "Write databases"],
    lastSync: new Date(Date.now() - 86400000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-openai",
    name: "OpenAI",
    category: "ai",
    status: "connected",
    description: "Access GPT models for text generation, analysis, and tool use.",
    permissions: ["Chat completions", "Embeddings", "Function calling"],
    lastSync: new Date(Date.now() - 120000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-anthropic",
    name: "Anthropic",
    category: "ai",
    status: "connected",
    description: "Access Claude models for complex reasoning and long-context tasks.",
    permissions: ["Messages API", "Tool use", "Vision"],
    lastSync: new Date(Date.now() - 120000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-google-ai",
    name: "Google AI",
    category: "ai",
    status: "connected",
    description: "Access Gemini models for multimodal and long-context tasks.",
    permissions: ["Generate content", "Vision", "Function calling"],
    lastSync: new Date(Date.now() - 120000).toISOString(),
    webhookUrl: undefined,
    isBuiltin: true,
  },
  {
    id: "int-linear",
    name: "Linear",
    category: "developer",
    status: "disconnected",
    description: "Manage Linear issues, cycles, and projects from OmegaBot tasks.",
    permissions: ["Read issues", "Create issues", "Update issues", "Manage projects"],
    lastSync: undefined,
    webhookUrl: undefined,
    isBuiltin: false,
  },
  {
    id: "int-jira",
    name: "Jira",
    category: "developer",
    status: "disconnected",
    description: "Create and manage Jira tickets, sprints, and epics.",
    permissions: ["Read issues", "Create issues", "Manage sprints"],
    lastSync: undefined,
    webhookUrl: undefined,
    isBuiltin: false,
  },
  {
    id: "int-gdrive",
    name: "Google Drive",
    category: "storage",
    status: "disconnected",
    description: "Read, create, and manage Google Drive files and folders.",
    permissions: ["Read files", "Create files", "Manage folders", "Share files"],
    lastSync: undefined,
    webhookUrl: undefined,
    isBuiltin: false,
  },
  {
    id: "int-hubspot",
    name: "HubSpot",
    category: "productivity",
    status: "pending",
    description: "Manage CRM contacts, deals, and marketing campaigns.",
    permissions: ["Read contacts", "Update contacts", "Read deals", "Create tasks"],
    lastSync: undefined,
    webhookUrl: undefined,
    isBuiltin: false,
  },
];

router.get("/integrations", (_req, res) => {
  const connected = INTEGRATIONS.filter((i) => i.status === "connected").length;
  res.json({ items: INTEGRATIONS, total: INTEGRATIONS.length, connectedCount: connected });
});

export default router;
